module.exports = {
  INIT_DATA: [
    [
      1,
      'Angular Developer',
      '',
      'https://angular.io/guide/developer-guide-overview',
      0,
    ],
    [
      2,
      'Typescript Developer',
      '',
      'https://www.typescriptlang.org/docs/handbook/intro.html',
      1,
    ],
    [3, 'Javascript Developer', '', 'https://www.w3schools.com/js/', 2],
    [
      4,
      'Types and Interfaces',
      '',
      'https://www.typescriptlang.org/play#example/types-vs-interfaces',
      2,
    ],
    [5, 'SCSS', '', 'https://www.w3schools.com/sass/', 1],
    [6, 'CSS', '', 'https://www.w3schools.com/css/', 5],
    [7, 'HTML', '', 'https://www.w3schools.com/html/', 6],
    [
      8,
      'UI/UX Design',
      '',
      'https://www.coursera.org/specializations/ui-ux-design',
      6,
    ],
    [
      9,
      'React Developer',
      '',
      'https://reactjs.org/docs/getting-started.html',
      0,
    ],
    [
      10,
      'Typescript Developer',
      '',
      'https://www.typescriptlang.org/docs/handbook/intro.html',
      9,
    ],
    [11, 'Javascript Developer', '', 'https://www.w3schools.com/js/', 10],
    [
      12,
      'Types and Interfaces',
      '',
      'https://www.typescriptlang.org/play#example/types-vs-interfaces',
      10,
    ],
    [13, 'SCSS', '', 'https://www.w3schools.com/sass/', 9],
    [14, 'CSS', '', 'https://www.w3schools.com/css/', 13],
    [15, 'HTML', '', 'https://www.w3schools.com/html/', 13],
    [
      16,
      'UI/UX Design',
      '',
      'https://www.coursera.org/specializations/ui-ux-design',
      14,
    ],
  ],
};
